# Generated by Django 2.1.7 on 2019-04-06 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('mrp', models.FloatField()),
                ('batch_num', models.PositiveIntegerField()),
                ('batch_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
