# Generated by Django 2.2 on 2019-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Store Assistant'), ('M', 'Store Manager')], max_length=100),
        ),
    ]
